name: 'Read file'
description: 'Read contents of an arbitrary file.'
author: 'Igor Dimitrijević (igorskyflyer)'
branding:
  icon: 'file-text'
  color: 'purple'

inputs:
  path:
    description: 'File path'
    required: true
    default: ''

outputs:
  content:
    description: 'File contents'

runs:
  using: 'node20'
  main: 'dist/index.mjs'
